### ISSUE TITLE
Debian Linux?

### ISSUE THREAD

**Issue by ksya** [karloygard/xcomfortd#6]
Is it supposed to work on debian linux? I only have the /13 stick and it says it cannot find the xcomfort stick.

**Comment by karloygard** [comment]
Yes, the /13 stick is only intended for configuring the devices and setting things up with the MRF software, not for switching lights on/off, etc. Eaton have made it so that you kinda need both the /13 and /14. The protocol that the /13 uses is more complicated; I did try to reverse engineer it, there's some code in the  ckoz0013 folder, but I abandoned that attempt.

**Comment by Geving** [comment]
I'm using the /14 (and to some extent, the much older /03) on a Raspberry Pi running raspbian, so I imagine it should work on most debian machines. [EDIT: Sorry, I just re-read your post, and noticed that you have the 13 and not the 14. Sorry about that!]

As for the document; WOW! This is an awesome find! I'm half way expecting it to be watermaked as "Internal use only!".

**Comment by deve87** [comment]
I have the same problem. But only I got the /14 stick. It shows no xComfort USB device.
